InventoryQuickCRUD/InventoryQuickCRUD/Models/Empleado.cs
using System.ComponentModel.DataAnnotations;

namespace InventoryQuickCRUD.Models
{
    public class Empleado
    {
        [Key]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Nombre Empleado")]
        public string Name { get; set; }
        [Display(Name = "Cargo")]
        public string Designation { get; set; }

        [DataType(DataType.MultilineText)]
        public string Address { get; set; }

        public DateTime? RecordCreation { get; set; }

        public DateTime? RecordUpdateOn { get; set; }

        public bool Estate { get; set; } = true;

    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Models/ErrorViewModel.cs
namespace InventoryQuickCRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Models/UsuarioRegistrado.cs
using Microsoft.AspNetCore.Identity;
using System.ComponentModel.DataAnnotations.Schema;


namespace InventoryQuickCRUD.Models
{
    [Table("Usuario")]
    public class UsuarioRegistrado
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Pais { get; set; }
        public string CodigoPais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }
        public string Celular { get; set; }
        public bool Estado { get; set; } = true;
        public string? Url { get; set; }
    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Models/ViewModels/RegisterViewModels.cs
using System.ComponentModel.DataAnnotations;


namespace InventoryQuickCRUD.Models.ViewModels
{
    public class RegisterViewModels
    {
        public string Nombres { get; set; }
        public string Apellidos { get; set; }

        [Required(ErrorMessage = "La fecha de nacimiento es obligatoria")]
        [Display(Name = "Fecha de nacimiento")]
        public DateTime FechaNacimiento { get; set; }

        public string Pais { get; set; }
        public string CodigoPais { get; set; }
        public string Ciudad { get; set; }
        public string Direccion { get; set; }

        public string Celular { get; set; }
        public bool Estado { get; set; }

        [Required(ErrorMessage = "El email es obligatorio")]
        [EmailAddress]
        public string Email { get; set; }


        [Required(ErrorMessage = "la contraseña es obligatoria")]
        [StringLength(50, ErrorMessage = "El {0} debe estar almenos entre {2} caracteres de longitud", MinimumLength = 8)]
        [DataType(DataType.Password)]
        [Display(Name = "Contraseña")]
        public string Password { get; set; }


        [Required(ErrorMessage = "La confirmacion de la contraseña es obligatoria")]
        [Compare("Password", ErrorMessage = "La contraseña y confirmacion de contraseña no coinciden")]
        [DataType(DataType.Password)]
        [Display(Name = "Confirmar contraseña")]
        public string ConfirmPassword { get; set; }


        [Required(ErrorMessage = "La confirmacion de la contraseña es obligatoria")]

        [Url]
        public string URL { get; set; }

    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Controllers/CuentasController.cs
using Microsoft.AspNetCore.Mvc;

namespace InventoryQuickCRUD.Controllers
{
    public class CuentasController : Controller
    {


        public IActionResult Index()
        {
            return View();
        }
    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using InventoryQuickCRUD.Data;
using InventoryQuickCRUD.Models;
using Microsoft.AspNetCore.Http;


namespace InventoryQuickCRUD.Controllers
{
    public class EmpleadosController : Controller
    {
        private readonly ApplicationDbContext _context;

        public EmpleadosController(ApplicationDbContext context)
        {
            _context = context;
        }
        // GET: EmployeesController
        public ActionResult Index()
        {
            IEnumerable<Empleado> colEmpleados = _context.Empleados.Where(s => s.Estate == true);// Código refactorizado para retornar 
            return View(colEmpleados);
        }

        // GET: EmployeesController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: EmployeesController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: EmployeesController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Empleado empleado)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    _context.Employees.Add(empleado);
                    _context.SaveChanges();
                    TempData["ResultOk"] = "Datos agregados satisfactoriamente";

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();//empobj
            }
        }

        // GET: EmployeesController/Edit/5
        public ActionResult Edit(int id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var empleadofromdb = _context.Empleados.Find(id);
            if (empleadofromdb == null)
            {
                return NotFound();
            }
            return View(empleadofromdb);
        }

        // POST: EmployeesController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Empleado empleado)
        {


            try
            {
                if (ModelState.IsValid)
                {
                    _context.Empleados.Update(empleado);
                    _context.SaveChanges();
                    TempData["ResultOk"] = "Datos actualizados satisfactoriamente";

                }
                return RedirectToAction("Index");
            }
            catch
            {
                return View();//empobj
            }
        }

        // GET: EmployeesController/Delete/5
        public ActionResult Delete(int id)
        {
            if (id == null || id <= 0)
            {
                return NotFound();
            }
            var empleadofromdb = _context.Empleados.Find(id);
            if (empleadofromdb == null)
            {
                return NotFound();
            }
            return View(empleadofromdb);
        }

        // POST: EmployeesController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int? id)
        {

            try
            {
                var empleadofromdb = _context.Empleados.Find(id);




                if (empleadofromdb == null)
                {
                    return NotFound();

                }
                // _context.Employees.Remove(employeefromdb); // Refactorizado para inactivar el usuario. No eliminarlo 
                empleadofromdb.Estate = false;
                _context.Empleados.Update(empleadofromdb);

                _context.SaveChanges();
                TempData["ResultOk"] = "Datos eliminados satisfactoriamente";
                return RedirectToAction("Index");
            }
            catch
            {
                return View(); //empobj
            }
        }
    }
   
}

InventoryQuickCRUD/InventoryQuickCRUD/Controllers/HomeController.cs
using InventoryQuickCRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace InventoryQuickCRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Controllers/ProductosController.cs
using Microsoft.AspNetCore.Mvc;

namespace InventoryQuickCRUD.Controllers
{
    public class ProductosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InventoryQuickCRUD/InventoryQuickCRUD/Views/Empleados/Create.cshtml
@model Empleado

<div class= "container   box-shadow p-5" >

	<div>
	<h2>Agregar empleado</h2>
	</div>

	<form method="post"  asp-controller="Employees" asp-action = "Create">
		<div asp-validation-summary="All"> </div>
		<div class= "form-row">
			<div class="form-group col-md-6"> 
				<label asp-for="Name">Nombre del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Name" placeholder="Ingrese el nombre del empleado"/>
				<span asp-validation-for="Name" class="alert-danger"></span>
			</div>

			
			<div class="form-group col-md-6"> 
				<label asp-for="Designation">Cargo del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Designation" placeholder="Ingrese el cargo del empleado"/>
				<span asp-validation-for="Designation" class="alert-danger"></span>
			</div>

			
			<div class="form-group col-md-6"> 
				<label asp-for="Address">Dirección</label>
				<input type="text" class="form-control mb-3 " asp-for="Address" placeholder="Ingrese la direccion"/>
				<span asp-validation-for="Address" class="alert-danger"></span>
			</div>

			<div class="form-group col-md-6 mb-3"> 
				<label asp-for="RecordCreation">Fecha de Creacion</label>
				<input type="datetime-local" class="form-control mb-3 " asp-for="RecordCreation" />
				<span asp-validation-for="RecordCreation" class="alert-danger"></span>
			</div>



		</div>

		<button type="submit" class="btn btn-primary btn-lg p-2">

			<i class="bi bi-file-plus-fill"></i>
			Guardar
		</button>

		<a asp-controller="Employees" asp-action="Index" class="btn btn-lg btn-warning p-2 "> Regresar </a>
	</form>
</div>

@section Scripts{

	@{
		<partial name="_ValidationScriptsPartial"/>
	}


}

InventoryQuickCRUD/InventoryQuickCRUD/Views/Empleados/Delete.cshtml
@model Empleado

<div class= "container   box-shadow p-5" >
	<div>

		<h2>Eliminar empleado</h2>
	</div>
 


	<form method="post"  asp-controller="Employees" asp-action = "Delete">
		@*<div asp-validation-summary="All"> </div>*@

		<input asp-for =Id hidden />

		<div class= "form-row">
			<div class="form-grup col-md-6"> 
				<label asp-for="Name">Nombre del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Name" disabled />
				@*<span asp-validation-for="Name" class="alert-danger"></span>*@
			</div>

			
			<div class="form-grup col-md-6"> 
				<label asp-for="Designation">Cargo del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Designation" disabled />
				@*<span asp-validation-for="Designation" class="alert-danger"></span>*@
			</div>

			
			<div class="form-grup col-md-6"> 
				<label asp-for="Address">Dirección</label>
				<input type="text" class="form-control mb-3 " asp-for="Address" disabled/>
			@*	<span asp-validation-for="Address" class="alert-danger"></span>*@
			</div>

			<div class="form-grup col-md-6"> 
				<label asp-for="RecordCreation">Fecha de Creacion</label>
				<input type="datetime-local" class="form-control mb-3 " asp-for="RecordCreation" disabled />
			@*	<span asp-validation-for="RecordCreation" class="alert-danger"></span>*@
			</div>


			<div class="form-grup col-md-6"> 
				<label asp-for="RecordUpdateOn">Fecha de Modificacion</label>
				<input type="datetime-local" class="form-control mb-3 " asp-for="RecordUpdateOn" disabled />
			@*	<span asp-validation-for="RecordCreation" class="alert-danger"></span>*@
			</div>


		</div>

		<button type="submit" class="btn btn-primary btn-lg p-2">

			<i class="bi bi-file-plus-fill"></i>
			Eliminar
		</button>

		<a asp-controller="Employees" asp-action="Index" class="btn btn-lg btn-warning p-2 "> Regresar </a>
	</form>
</div>

@section Scripts{

	@{
		<partial name="_ValidationScriptsPartial"/>
	}


}

InventoryQuickCRUD/InventoryQuickCRUD/Views/Empleados/Edit.cshtml
@model Empleado

<div class= "container   box-shadow p-5" >

	<div>
	<h2>Editar un empleado</h2>
	</div>

	<form method="post"  asp-controller="Employees" asp-action = "Edit">



		<div asp-validation-summary="All"> </div>


		<div class= "form-row">
			<div class="form-group col-md-6"> 
				<label asp-for="Name">Nombre del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Name" />
				<span asp-validation-for="Name" class="alert-danger"></span>
			</div>

			
			<div class="form-group col-md-6"> 
				<label asp-for="Designation">Cargo del empleado:</label>
				<input type="text" class="form-control mb-3 " asp-for="Designation" />
				<span asp-validation-for="Designation" class="alert-danger"></span>
			</div>

			
			<div class="form-group col-md-6"> 
				<label asp-for="Address">Dirección</label>
				<input type="text" class="form-control mb-3 " asp-for="Address"/>
				<span asp-validation-for="Address" class="alert-danger"></span>
			</div>

			<div class="form-group col-md-6 mb-3"> 
				<label asp-for="RecordUpdateOn">Fecha de Modificacion:</label>
				<input type="datetime-local" class="form-control mb-3 " asp-for="RecordUpdateOn" />
				<span asp-validation-for="RecordUpdateOn" class="alert-danger"></span>
			</div>

			
			<div class="form-group col-md-6 mb-3">

				<input type="hidden" class="form-control " asp-for="RecordCreation" />

			</div>


		</div>

		<button type="submit" class="btn btn-primary btn-lg p-2">

			<i class="bi bi-file-plus-fill"></i>
			Actualizar
		</button>

		<a asp-controller="Employees" asp-action="Index" class="btn btn-lg btn-warning p-2 "> Regresar </a>
	</form>
</div>

@section Scripts{

	@{
		<partial name="_ValidationScriptsPartial"/>
	}


}

InventoryQuickCRUD/InventoryQuickCRUD/Views/Empleados/Index.cshtml
 @model IEnumerable<Empleado>

@{
	ViewData["Title"]="Index";
}

@if(TempData["ResultOk"]!=null ){
	<h1 class="alert-success">@TempData["ResultOk"]</h1>
}


<div class="container box-shadow p-5">

	<h1 class="text-center ab-3"> Control de Empleados Dulce Pooh </h1>

	<div class="col mb-3">

		<a aps-controller="Employees" asp-action = "Create" class="btn btn-lg btn-primary" >
			<i class="bi bi-file-plus-fill">
				Adicionar empleado
			</i>
		</a>
	</div>

	<table class="table table-bordered table-hover">

		<thead>
			<tr>
				<th scope="col">Nombre Empleado</th>
				<th scope="col">Cargo</th>
				<th scope="col">Direccion</th>
				<th scope="col">Fecha C</th>
				<th></th>
			</tr>

		</thead>

		<tbody>
			@foreach (var item in Model)
			{
				<tr>
					<td width="20%">@item.Name</td>
					<td width="20%">@item.Designation</td>
					<td width="25%">@item.Address</td>
					<td width="20%">@item.RecordCreation</td>


					<td >
						
						<div role="group" class="w-60 btn-group">
							 
							<a asp-controller="Employees" asp-action= "Edit" asp-route-id = "@item.Id" class="btn btn-sm btn-primary" > <i class="bi bi-pencil-square"></i> Editar </a>&nbsp;



							<a asp-controller="Employees" asp-action= "Delete" asp-route-id = "@item.Id" class="btn btn-sm btn-danger" > <i class="bi bi-trash-fill"></i>Eliminar </a>

						</div>
					
					</td>
				</tr>
			}


		</tbody>

	</table>

</div>

InventoryQuickCRUD/InventoryQuickCRUD/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

InventoryQuickCRUD/InventoryQuickCRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InventoryQuickCRUD</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/InventoryQuickCRUD.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplicationEmployees.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">InventoryQuickCRUD</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InventoryQuickCRUD - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>